config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  resources :workouts, only: [:index, :show, :update, :new, :create] do
    resources :workout_sessions, only: [:new, :create]
  end

  resources :workout_sessions, only: [:index, :show] do
    member do
      get :view
    end
    resources :exercises, only: [:show]
  end

  namespace :videos do
    resources :exercises, only: [:show]
  end

  resources :exercises, only: [:index, :show, :update, :create, :new] do
    member do
      get :compare
    end
    resources :exercise_sets, only: [:create]
  end
  resources :exercise_sets, only: [:show, :update]

  get 'calendar', to: "pages#calendar", as: :calendar
  get 'dashboard', to: "pages#dashboard", as: :dashboard

end

app/models/workout.rb
class Workout < ApplicationRecord
  belongs_to :user, optional: true
  has_many :exercise_assignments, dependent: :destroy
  has_many :workout_sessions
  has_many :exercises, through: :exercise_assignments
  has_many :exercise_sets, through: :workout_sessions

  validates :name, presence: true
  validates :category, presence: true

  include PgSearch::Model

  pg_search_scope :search_by,
    against: [:name, :category],
    associated_against: {
      user: [:username]
    },
    using: {
      tsearch: { prefix: true } # <-- now `superman batm` will return something!
    }

end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController

  def index
    @workouts = Workout.all
    @workout = Workout.new
  end

  def show
    @workout = Workout.find(params[:id])
    @workout_sessions = @workout.workout_sessions
    @exercises = @workout.exercises
  end


  def new
    @workout = Workout.new
  end

  def update

  end

  def create
    @workout = Workout.new(workout_params)
    @workout.user = current_user
    if @workout.save
      redirect_to workouts_path, notice: "Workout was successfully created"
    else
      render 'new', status: :unprocessable_entity
    end
  end

  private

  def workout_params
    params.required(:workout).permit(:name, :category)
  end
end

app/views/workouts/index.html.erb
<h1 class="custom-margin">Workout List</h1>
<div class="cards">
  <% @workouts.each do |workout| %>
    <%= render 'shared/workout_card', workout: workout %>
  <% end %>
</div>



<div class="fab-container">
  <%= link_to new_workout_path, class: 'fab' do %>
    <i class="fas fa-plus"></i> <!-- Font Awesome icon -->
  <% end %>
</div>

app/views/workouts/new.html.erb
<div class="form-container">
  <%= simple_form_for @workout do |form| %>
    <div class="mb-3">
      <%= form.input :name, input_html: { class: 'form-control' } %>
    </div>
    <div class="mb-3">
      <%= form.input :category, input_html: { class: 'form-control' } %>
    </div>
    <div class="d-grid">
      <%= form.submit "Create Workout", class: 'create-form-button' %>
    </div>
  <% end %>
</div>

app/views/workouts/show.html.erb
  <% @exercises.each_with_index do |exercise, index| %>
    <%= render 'shared/exercise_card', exercise: exercise, index_exercise: index, workout_session: @workout_session %>
  <% end %>

app/views/workouts/show_not_used.html.erb
<div>
  <h1><%= @workout.name %></h1>
</div>

<ul class="nav nav-tabs" id="myTab" role="tablist">
  <li class="nav-item" role="presentation">
    <button class="nav-link active" id="workout-tab" data-bs-toggle="tab" data-bs-target="#workout-tab-pane" type="button" role="tab" aria-controls="workout-tab-pane" aria-selected="true">Workout</button>
  </li>
  <li class="nav-item" role="presentation">
    <button class="nav-link" id="history-tab" data-bs-toggle="tab" data-bs-target="#history-tab-pane" type="button" role="tab" aria-controls="history-tab-pane" aria-selected="false">History</button>
  </li>
  <li class="nav-item" role="presentation">
    <button class="nav-link" id="analytics-tab" data-bs-toggle="tab" data-bs-target="#analytics-tab-pane" type="button" role="tab" aria-controls="analytics-tab-pane" aria-selected="false">Analytics</button>
  </li>
</ul>
<div class="tab-content" id="myTabContent">
  <div class="tab-pane fade show active" id="workout-tab-pane" role="tabpanel" aria-labelledby="workout-tab" tabindex="0">

  </div>

  <div class="tab-pane fade" id="history-tab-pane" role="tabpanel" aria-labelledby="history-tab" tabindex="0">
    <div class="cards">
      <% @workout_sessions.each do |workout_session| %>
        <%= render 'shared/workout_session_card', workout_session: workout_session %>
      <% end %>
    </div>
  </div>
  <div class="tab-pane fade" id="analytics-tab-pane" role="tabpanel" aria-labelledby="analytics-tab" tabindex="0">...</div>
</div>