config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  resources :workouts, only: [:index, :show, :update, :new, :create] do
    resources :workout_sessions, only: [:new, :create]
  end

  resources :workout_sessions, only: [:index, :show] do
    member do
      get :view
    end
    resources :exercises, only: [:show]
  end

  namespace :videos do
    resources :exercises, only: [:show]
  end

  resources :exercises, only: [:index, :show, :update, :create, :new] do
    member do
      get :compare
    end
    resources :exercise_sets, only: [:create]
  end
  resources :exercise_sets, only: [:show, :update]

  get 'calendar', to: "pages#calendar", as: :calendar
  get 'dashboard', to: "pages#dashboard", as: :dashboard

end

app/views/shared/_cl_video_tag.html.erb
<div>
  <% if exercise_set.video.attached? %>
    <%= cl_video_tag exercise_set.video.key, width: 390, resource_type: 'raw', controls: false, :playsinline => true, muted: true, autoplay: true, class: 'videoreplay' %>
  <% end %>
  <%= hidden_field_tag :exercise_id, exercise_set.id %>
</div>

app/views/shared/_compare_display_card.html.erb
<div class="compare-display-card-parent">
  <div class="compare-display-card">
    <div class="pe-1">
      <%# div 1 exercise and descriptions %>
      <%= exercise_set&.workout_session&.start_time&.strftime("%A, %b %d") %>
      <%# excercise name here: %>
    </div>
    <%# each exercise_sets input and total set here: %>
    <div data-controller="total-set-count" class="sets">
      <%# sub exercise_sets form here: %>
      <div class="d-flex justify-space-between">
        <%# get the number of exercise.sets store them in a variable, use that variablee to get the last two instances of the exercise_sets %>
        <p class="me-2">sets:</p>
        <% exercise_set&.workout_session&.exercise_sets&.where(exercise: exercise)&.each do |set| %>
          <p class="<%= set == exercise_set ? 'set-highlite': '' %> me-2"> <%= set.reps %> </p>
        <% end %>
      </div>
    </div>
  </div>
  <% if exercise_set&.video&.attached? %>
    <%# if exercise_set.workout_session.start_time.today? %>
    <% if Cloudinary::Api.resources(resource_type: 'raw')['resources'].map { |hash| hash['public_id'].split('.').first }.include?(exercise_set.video.key) %>
      <%= cl_video_tag exercise_set&.video&.key, resource_type: 'raw', controls: false, :playsinline => true, muted: true, autoplay: true, loop: true, class: "video-wrapper" %>
    <% else %>
      <%= cl_video_tag exercise_set&.video&.key, resource_type: 'video', controls: false, :playsinline => true, muted: true, autoplay: true, loop: true, class: "video-wrapper" %>
    <% end %>
  <% end %>
</div>

app/views/shared/_exercise_card.html.erb
<div>
    <%# excercise name here: %>
  <div class="exercise-card-items" >
    <div class="div-left"><%# div1 %>
      <h2 class="<%= exercise.exercise_type %>"><%= exercise.name %></h2>

      <div class="d-flex mt-2">
        <%# rest time:here %>
        <h4 class="exercise-info me-3">
          <% if exercise.lower_reps.nil? && exercise.upper_reps.nil?  %>
            <i class="fa-solid fa-stopwatch"></i> <%= exercise.hold_time %> s hold
          <% else %>
            <i class="fa-solid fa-repeat"></i> <%= exercise.lower_reps %>-<%= exercise.upper_reps %> reps
          <% end %>
        </h4>
        <h4 class="exercise-info"><i class="fa-regular fa-circle-pause"></i> <%= exercise.rest %>s rest</h4>
      </div>
      <div>
        <div><h4 class="exercise-info set-text"><i class="fa-solid fa-dumbbell"></i> <%= exercise.sets %> sets to do:</h4></div>

        <% sets_done = workout_session.sets_done(exercise) %>
        <div class='set'>
          <% sets_done.each do |set_done| %>
            <%= link_to set_done.reps , exercise_set_path(set_done), class:"rep-num-button" %>
          <% end %>

          <% (exercise.sets - sets_done.count).times do |i| %>
            <%#= link_to workout_session_exercise_path(workout_session, exercise), class:"text-decoration-none" do %>
              <p class='rep-num-button-light'>
                <% if exercise.lower_reps.nil? %>
                  <%= exercise.hold_time %>
                <% else %>
                  <%= exercise.lower_reps %>
                <% end %>
              </p>
            <%# end %>
          <% end %>
        </div>

        <%# total # of sets display here: %>
        <div>
          <% total = 0 %>
          <% sets_done.each do |set_done| %>
            <% total += set_done.reps unless set_done.reps.nil? %>
          <% end %>
          <span class="rep-num-total">Volume: <%= total %></span>
        </div>
      </div>
    </div>

    <div class="div-right"><%# div2 %>
      <div><%# sets and reps in this div: %>
        <div>
          <%# <span class="exercise-info"><%= exercise.sets %>
            <%# sets x  %>
          <%# </span>  %>

        </div>

      </div>

      <div class="progress-done"><%# 1/5 done in this div: %>
        <% if sets_done.count == exercise.sets %>
          <h4><i class="fa-sharp fa-solid fa-check fa-2xl"></i></h4>
        <% else %>
          <%= link_to workout_session_exercise_path(workout_session, exercise), class:"text-decoration-none text-white delayed" do %>
            <h2><%= sets_done.count %>/<%= exercise.sets %></h2>
            <h6>done</h6>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_exercise_done.html.erb
<div class="exercise-sets-card">
  <div class="sets">
    <div class="pe-1 border-light-subtle">
      <h6><strong><%= exercise.name %></strong></h6>
    </div>
    <div class="d-flex">
      <% sets_done = workout_session.sets_done(exercise) %>
      <div class='set' style="display: inline-flex;">
        <% sets_done.each do |set_done| %>
          <%= link_to set_done.reps , exercise_set_path(set_done), class:"rep-num-button" %>
        <% end %>
        <% (exercise.sets - sets_done.count).times do |i| %>
          <p class='rep-num-button-light'>
            <% if exercise.lower_reps.nil? %>
              <%= exercise.hold_time %>
            <% else %>
              <%= exercise.lower_reps %>
            <% end %>
          </p>
        <% end %>
      </div>
    </div>
  </div>
  <%= link_to 'Compare', compare_exercise_path(exercise), class: 'btn btn-cool' %> <!-- Button here -->
</div>

app/views/shared/_exercise_list_card.html.erb
<%= link_to compare_exercise_path(exercise) do %>
  <div class="card-product">
    <div class="card-product-infos">
      <h2 class="exercise-title"><%= exercise.name %></h2>
      <p><%= exercise.category %></p>
    </div>
  </div>
<% end %>

app/views/shared/_exercise_set_form.html.erb
<div>
  <%= simple_form_for([exercise, set], html: {data: { record_video_target:"form"}}) do |f| %>
    <div class="custom-set-form">
      <%= f.input :reps, label: false, input_html: {class: 'set-value', id: 'sets-form', value: exercise.default_reps, data: {record_video_target: "inputReps", action: 'change->record_video#updateSet'}}  %>
      <%= f.input :workout_session_id, as: :hidden, input_html: { value: workout_session.id} %>
      <%# unless @sets_done.count >= @exercise.sets - 1 %>
      <%= f.submit 'Save', data: {record_video_target: 'submit'}, class: 'create-set-btn'%>
    </div>
  <% end %>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_how_to_link.html.erb
<div>
  <%= link_to exercise.ref_video_link do %>
    <span class="rounded-button delayed">how to <i class="fa-solid fa-link"></i></span>
  <% end %>
</div>

app/views/shared/_ios_pwa_links.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="<%= image_path 'icons/apple-icon-57x57.png' %>">
<link rel="apple-touch-icon" sizes="60x60" href="<%= image_path 'icons/apple-icon-60x60.png' %>">
<link rel="apple-touch-icon" sizes="72x72" href="<%= image_path 'icons/apple-icon-72x72.png' %>">
<link rel="apple-touch-icon" sizes="76x76" href="<%= image_path 'icons/apple-icon-76x76.png' %>">
<link rel="apple-touch-icon" sizes="114x114" href="<%= image_path 'icons/apple-icon-114x114.png' %>">
<link rel="apple-touch-icon" sizes="120x120" href="<%= image_path 'icons/apple-icon-120x120.png' %>">
<link rel="apple-touch-icon" sizes="144x144" href="<%= image_path 'icons/apple-icon-144x144.png' %>">
<link rel="apple-touch-icon" sizes="152x152" href="<%= image_path 'icons/apple-icon-152x152.png' %>">
<link rel="apple-touch-icon" sizes="180x180" href="<%= image_path 'icons/apple-icon-180x180.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= image_path 'icons/favicon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="96x96" href="<%= image_path 'icons/favicon-96x96.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= image_path 'icons/favicon-16x16.png' %>">

app/views/shared/_navbar.html.erb
<ul class="navbar-custom navbar-bottom">
  <li><%= link_to root_path do %>
    <i class="fas fa-home"></i>
  <% end %></li>
  <li><%= link_to dashboard_path do %>
    <i class="fas fa-tachometer-alt"></i>
  <% end %></li>
  <li><%= link_to workout_sessions_path do %>
    <i class="fas fa-history"></i>
  <% end %></li>
  <li><%= link_to exercises_path do %>
    <i class="fas fa-balance-scale"></i>
  <% end %></li>
</ul>

app/views/shared/_progress_bar.html.erb
<div>
  <div class="step-progress">
    <% exercises.each_with_index do |exercise, i| %>
      <% exercise_num = i + 1 %>

      <% if @exercise_completed[exercise.name] %>
        <div class="bullet-completed-<%= exercise.exercise_type %>"><%= exercise.name.first %></div>
      <% else %>
        <div class="bullet"><%= exercise_num %></div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/shared/_workout_card.html.erb
<div class="card-products">
  <%= image_tag "workout_#{index + 1}.jpg", alt: "text" %>
  <div class="card-product-infos">
    <h2><%= workout.name %></h2>
    <p><%= workout.category %></p>
  </div>
  <%= simple_form_for([workout, @workout_sess]) do |f| %>
  <div class="button-container">
    <%=  f.submit 'Start', class: 'btn-sporty' %>
  </div>
  <% end %>
</div>

app/views/shared/_workout_session_card.html.erb
<%= link_to view_workout_session_path(workout_session), class: 'text-decoration-none' do %>
  <div class="card-product">
    <div class="card-product-infos">
      <h2 class= "m-0"><%= workout_session.workout.category %>, <%= workout_session.workout.name %> </h2>
      <p><%=workout_session.start_time.strftime("%A, %b %d %Y") %></p>
    </div>
  </div>
<% end %>

app/views/shared/_workout_session_info_form.html.erb
<%= simple_form_for @workout_session do |f| %>
  <%= f.input :sleep_time %>
  <%= f.input :bodyweight %>
  <%# <%= f.submit 'Submit', class: 'btn btn-info mt-2' %>
<% end %>