config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  resources :workouts, only: [:index, :show, :update, :new, :create] do
    resources :workout_sessions, only: [:new, :create]
  end

  resources :workout_sessions, only: [:index, :show] do
    member do
      get :view
    end
    resources :exercises, only: [:show]
  end

  namespace :videos do
    resources :exercises, only: [:show]
  end

  resources :exercises, only: [:index, :show, :update, :create, :new] do
    member do
      get :compare
    end
    resources :exercise_sets, only: [:create]
  end
  resources :exercise_sets, only: [:show, :update]

  get 'calendar', to: "pages#calendar", as: :calendar
  get 'dashboard', to: "pages#dashboard", as: :dashboard

end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController


  def index
    if params[:category]
      @exercises = Exercise.where(category: params[:category])
    else
      @exercises = Exercise.all
    end
  end

  def show
    @exercise = Exercise.find(params[:id])
    @workout_session = WorkoutSession.find(params[:workout_session_id])
    @exercises = @workout_session.exercises
    # display progress of current workout_session
    # @exercise_sets = @workout_session.exercise_sets
    # get exercise_set
    # @exercise_set = @exercises.exercise_set
    @exercise_sets = @workout_session.exercise_sets.group_by(&:exercise)

    @exercise_completed = {}
    @workout_session.exercises.each do |exercise|
      @exercise_completed[exercise.name] = false
    end
    @exercise_sets.each do |exercise, exercise_sets|
      @exercise_completed[exercise.name] = exercise_sets.length >= exercise.sets
    end
  end

  def compare
    @exercise = Exercise.find(params[:id])
    @workout_sessions_hash = @exercise.exercise_sets.group_by(&:workout_session)
    if params[:first_date] && params[:second_date]
      @last_workout_session = @workout_sessions_hash.keys.find { |workout_session| workout_session.id == params[:first_date].to_i}
      @last_exercise_set = @workout_sessions_hash[@last_workout_session] || []

      @second_last_workout_session = @workout_sessions_hash.keys.find { |workout_session| workout_session.id == params[:second_date].to_i }
      @second_last_exercise_set = @workout_sessions_hash[@second_last_workout_session] || []
    else
      @last_two_sessions = @workout_sessions_hash.keys.sort.last(2)
      @last_exercise_set = @workout_sessions_hash[@last_two_sessions.last] || []
      @second_last_exercise_set = @workout_sessions_hash[@last_two_sessions[0]] || []
    end
      @max_sets = @exercise.sets

    @data_hash_sum = Hash.new(0)
    current_user.workout_sessions.each do |workout_session|
      reps = workout_session.exercise_sets.where(exercise: @exercise).sum { |exercise_set| exercise_set.reps }
      @data_hash_sum[workout_session.start_time] += reps if reps.positive?
    end


    @data_hash_by_year = {}
    @data_hash_sum.each do |date, sum|
      @data_hash_by_year[date.year] = {} if @data_hash_by_year[date.year].nil?
      @data_hash_by_year[date.year][date] = sum
    end

    @data_hash_average_per_set = Hash.new(0)
    current_user.workout_sessions.each do |workout_session|
      exercise_sets = workout_session.exercise_sets.where(exercise: @exercise)
      @exercise.sets.times do |set_number|
        @data_hash_average_per_set[set_number + 1] += exercise_sets[set_number].reps unless exercise_sets[set_number].nil?
      end
    end

    @total_workout_sessions_with_exercise = 0
    current_user.workout_sessions.each do |workout_session|
      @total_workout_sessions_with_exercise += workout_session.exercise_sets.where(exercise: @exercise).count
    end

    @total_workout_sessions_with_exercise = @total_workout_sessions_with_exercise / @exercise.sets

    @exercise.sets.times do |set_number|
      @data_hash_average_per_set[set_number + 1] = @data_hash_average_per_set[set_number + 1].fdiv(@total_workout_sessions_with_exercise).round(2)
    end
  end

  def new

  end

  def create

  end

  def update

  end

end

app/controllers/videos/exercises_controller.rb
class Videos::ExercisesController < ApplicationController
  def show
    @exercise = Exercise.find(params[:id])
    @workout_sessions_hash = @exercise.exercise_sets.group_by(&:workout_session)
    if params[:first_date] && params[:second_date]
      @last_workout_session = @workout_sessions_hash.keys.find { |workout_session| workout_session.start_time == params[:first_date] }
      @last_exercise_set = @workout_sessions_hash[@last_workout_session]

      @second_last_workout_session = @workout_sessions_hash.keys.find { |workout_session| workout_session.start_time == params[:second_date] }
      @second_last_exercise_set = @workout_sessions_hash[@second_last_workout_session]
    else
      @last_two_sessions = @workout_sessions_hash.keys.sort.last(2)
      @last_exercise_set = @workout_sessions_hash[@last_two_sessions.last]
      @second_last_exercise_set = @workout_sessions_hash[@last_two_sessions[0]]
    end
  end
end

app/views/exercises/compare.html.erb
<div class="compare-container">
  <h1> <%= @exercise.name %> </h1>
  <!-- Nav tabs -->
  <div class="back-button-container d-flex justify-content-between align-items-center">
    <ul class="nav nav-pills" id="myTab" role="tablist">
      <li class="nav-item" role="presentation">
        <button class="nav-link active nav-tabs-custom" id="home-tab" data-bs-toggle="tab" data-bs-target="#home" type="button" role="tab" aria-controls="home" aria-selected="true" >Video</button>
      </li>
      <li class="nav-item" role="presentation">
        <button class="nav-link nav-tabs-custom" id="chart-tab" data-bs-toggle="tab" data-bs-target="#chart" type="button" role="tab" aria-controls="chart" aria-selected="false">Analyse</button>
      </li>
    </ul>
    <button type="button" class="btn btn-sporty ms-auto py-2" onclick="window.history.back();">
      <i class="bi bi-arrow-left"></i> Back
    </button>
  </div>
  <!-- Tab panes -->
  <div class="tab-content" id="myTabContent">
    <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
      <form action="/exercises/<%= @exercise.id %>/compare" method="GET" class="date-select">
        <select name="first_date" id="">
          <% @workout_sessions_hash.keys.sort_by(&:start_time).reverse.each do |workout_session| %>
            <option value="<%= workout_session.id %>" <%= workout_session.id == params[:first_date].to_i ? "selected" : "" %>><%= workout_session.start_time.strftime(" %a, %b %e, %Y") %></option>
            <% end %>
            <%# <option value="" selected>Select date</option> %>
          </select>
          <select name="second_date" id="">
            <% @workout_sessions_hash.keys.sort_by(&:start_time).reverse.each do |workout_session| %>
              <option value="<%= workout_session.id %>" <%= workout_session.id == params[:second_date].to_i ? "selected" : "" %>><%= workout_session.start_time.strftime(" %a, %b %e, %Y") %></option>
              <% end %>
            </select>
            <button type="submit" class="me-2">View</button>
          </form>
          <div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="false">
            <div class="carousel-indicators">
              <% @max_sets.times do |index| %> <%=  %>
                <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="<%= index %>" class="<%= index == 0 ? "active" : "" %>" aria-current="<%= index == 0 %>" aria-label="Slide <%= index %>"></button>
              <% end %>
            </div>
            <div class="carousel-inner">
              <% @max_sets.times do |index| %>
                <div class="carousel-item <%= index == 0 ? "active" : "" %>">
                  <div class="video-wrapper">
                    <%= render 'shared/compare_display_card', exercise: @exercise, exercise_set: @last_exercise_set[index]%>
                    <%= render 'shared/compare_display_card', exercise: @exercise, exercise_set: @second_last_exercise_set[index]%>
                  </div>
                </div>
              <% end %>
              <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Previous</span>
              </button>
              <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Next</span>
              </button>
            </div>
          </div>
        </div>
        <div class="tab-pane fade" id="chart" role="tabpanel" aria-labelledby="chart-tab">
          <!-- Nav tabs -->
          <ul class="nav nav-pills mt-2" id="years" role="tablist">
            <li class="nav-item " role="presentation">
              <button class="nav-link active nav-tabs-custom" id="all-tab" data-bs-toggle="tab" data-bs-target="#all" type="button" role="tab" aria-controls="all" aria-selected="true">All</button>
            </li>
            <li class="nav-item" role="presentation">
              <button class="nav-link nav-tabs-custom" id="2024-tab" data-bs-toggle="tab" data-bs-target="#2024" type="button" role="tab" aria-controls="2024" aria-selected="false">2024</button>
            </li>
            <li class="nav-item" role="presentation">
              <button class="nav-link nav-tabs-custom" id="2023-tab" data-bs-toggle="tab" data-bs-target="#2023" type="button" role="tab" aria-controls="2023" aria-selected="false">2023</button>
            </li>
            <li class="nav-item" role="presentation">
              <button class="nav-link nav-tabs-custom" id="2022-tab" data-bs-toggle="tab" data-bs-target="#2022" type="button" role="tab" aria-controls="2022" aria-selected="false">2022</button>
            </li>
          </ul>
          <div class="tab-content" id="yearsContent">
            <div class="tab-pane fade show active" id="all" role="tabpanel" aria-labelledby="all-tab">
              <div style="overflow-x: auto; white-space: nowrap;">
                <%= line_chart @data_hash_sum, width: "200%", height: "580px", colors: ["#ff9574", "#ff9574"], library: {
                scales: {
                  x: {
                    ticks: {
                      color: "#FFFFFF" # Custom color for x-axis labels
                    }

                  },
                  y: {
                    ticks: {
                      color: "#FFFFFF" # Custom color for y-axis labels
                    },
                    title: {
                    display: true,
                    text: 'Total reps',
                    color: "#FFFFFF" # Set the x-axis title color
                    }
                  }
                },
                plugins: {
                  title: {
                        display: true,
                        text: "Volume over time", # Set the chart title text
                        color: '#FFFFFF',          # Set the chart title color
                        font: {
                          size: 18,             # Set the chart title font size
                          # weight: 'bold'      # Set the chart title font weight
                        },
                        padding: {
                          top: 15,              # Add padding above the title
                          bottom: 5            # Add padding below the title
                        }
                      }
                }
              } %>
              </div>
            </div>
            <div class="tab-pane fade" id="2024" role="tabpanel" aria-labelledby="2024-tab">
              <%= line_chart @data_hash_by_year[2024], width: "100%", height: "580px",colors: ["#ff9574", "#ff9574"], library: {
                scales: {
                  x: {
                    ticks: {
                      color: "#FFFFFF" # Custom color for x-axis labels
                    }

                  },
                  y: {
                    ticks: {
                      color: "#FFFFFF" # Custom color for y-axis labels
                    },
                    title: {
                    display: true,
                    text: 'Total Reps',
                    color: "#FFFFFF" # Set the x-axis title color
                    }
                  }
                },
                plugins: {
                  title: {
                        display: true,
                        text: "Volume for 2024", # Set the chart title text
                        color: '#FFFFFF',          # Set the chart title color
                        font: {
                          size: 18,             # Set the chart title font size
                          # weight: 'bold'      # Set the chart title font weight
                        },
                        padding: {
                          top: 15,              # Add padding above the title
                          bottom: 5            # Add padding below the title
                        }
                      }
                }
              } %>
            </div>
            <div class="tab-pane fade" id="2023" role="tabpanel" aria-labelledby="2023-tab">
              <%= line_chart@data_hash_by_year[2023], width: "100%", height: "580px", colors: ["#ff9574", "#ff9574"], library: {
                scales: {
                  x: {
                    ticks: {
                      color: "#FFFFFF" # Custom color for x-axis labels
                    }

                  },
                  y: {
                    ticks: {
                      color: "#FFFFFF" # Custom color for y-axis labels
                    },
                    title: {
                    display: true,
                    text: 'Total Reps',
                    color: "#FFFFFF" # Set the x-axis title color
                    }
                  }
                },
                plugins: {
                  title: {
                        display: true,
                        text: "Volume for 2023", # Set the chart title text
                        color: '#FFFFFF',          # Set the chart title color
                        font: {
                          size: 18,             # Set the chart title font size
                          # weight: 'bold'      # Set the chart title font weight
                        },
                        padding: {
                          top: 15,              # Add padding above the title
                          bottom: 5            # Add padding below the title
                        }
                      }
                }
              } %>
            </div>
            <div class="tab-pane fade" id="2022" role="tabpanel" aria-labelledby="2022-tab">
              <%= line_chart@data_hash_by_year[2022], width: "100%", height: "580px", colors: ["#ff9574", "#ff9574"], library: {
                scales: {
                  x: {
                    ticks: {
                      color: "#FFFFFF" # Custom color for x-axis labels
                    }

                  },
                  y: {
                    ticks: {
                      color: "#FFFFFF" # Custom color for y-axis labels
                    },
                    title: {
                    display: true,
                    text: 'Total Reps',
                    color: "#FFFFFF" # Set the x-axis title color
                    }
                  }
                },
                plugins: {
                  title: {
                        display: true,
                        text: "Volume for 2022", # Set the chart title text
                        color: '#FFFFFF',          # Set the chart title color
                        font: {
                          size: 18,             # Set the chart title font size
                          # weight: 'bold'      # Set the chart title font weight
                        },
                        padding: {
                          top: 15,              # Add padding above the title
                          bottom: 5            # Add padding below the title
                        }
                      }
                }
              } %>
            </div>
          </div>
          <%#= line_chart @exercise.exercise_sets.group(:reps).count, height: "380px" %>
        </div>
      </div>
    </div>

app/views/exercises/index.html copy.erb
<h1 class="custom-margin mb-3">Exercise List</h1>
<!-- Tab Navigation -->
<ul class="nav nav-pills category-list py-3 mb-3" id="pills-tab" role="tablist">
  <li class="nav-item" role="presentation">
    <%= link_to "Mobility", compare_exercise_path(category: 'Mobility'), remote: true, class: "nav-link active", id: "pills-mobility-tab", data: { bs_toggle: "pill", bs_target: "#pills-mobility" }, role: "tab", aria_controls: "pills-mobility", aria_selected: "true" %>
  </li>
  <li class="nav-item" role="presentation">
    <%= link_to "Skill", compare_exercise_path(category: 'Skills'), remote: true, class: "nav-link", id: "pills-skills-tab", data: { bs_toggle: "pill", bs_target: "#pills-skills" }, role: "tab", aria_controls: "pills-skills", aria_selected: "false" %>
  </li>

</ul>
<!-- Tab Content -->
<div class="tab-content" id="pills-tabContent">
  <div class="tab-pane fade show active" id="pills-mobility" role="tabpanel" aria-labelledby="pills-mobility-tab" tabindex="0">

  </div>
  <div class="tab-pane fade" id="pills-skills" role="tabpanel" aria-labelledby="pills-skills-tab" tabindex="0">


  </div>
</div>

app/views/exercises/index.html.erb
<h1 class="custom-margin mb-3">Exercise List</h1>
<!-- Tab Navigation -->
<ul class="nav nav-pills category-list py-3 mb-3" id="pills-tab" role="tablist">
  <li class="nav-item" role="presentation">
    <%= link_to "Mobility", exercises_path(category: 'Mobility'), remote: true, class: "nav-link active", id: "pills-mobility-tab", data: { bs_toggle: "pill", bs_target: "#pills-mobility" }, role: "tab", aria_controls: "pills-mobility", aria_selected: "true" %>
  </li>
  <li class="nav-item" role="presentation">
    <%= link_to "Skill", exercises_path(category: 'Skills'), remote: true, class: "nav-link", id: "pills-skills-tab", data: { bs_toggle: "pill", bs_target: "#pills-skills" }, role: "tab", aria_controls: "pills-skills", aria_selected: "false" %>
  </li>
  <li class="nav-item" role="presentation">
    <%= link_to "Upper Body", exercises_path(category: 'Push/Pull Upper Body'), remote: true, class: "nav-link", id: "pills-upperbody-tab", data: { bs_toggle: "pill", bs_target: "#pills-upperbody" }, role: "tab", aria_controls: "pills-upperbody", aria_selected: "false" %>
  </li>
  <li class="nav-item" role="presentation">
    <%= link_to "Core", exercises_path(category: 'Core'), remote: true, class: "nav-link", id: "pills-core-tab", data: { bs_toggle: "pill", bs_target: "#pills-core" }, role: "tab", aria_controls: "pills-core", aria_selected: "false" %>
  </li>
  <li class="nav-item" role="presentation">
    <%= link_to "Lower Body", exercises_path(category: 'Lower Body'), remote: true, class: "nav-link", id: "pills-lowerbody-tab", data: { bs_toggle: "pill", bs_target: "#pills-lowerbody" }, role: "tab", aria_controls: "pills-lowerbody", aria_selected: "false" %>
  </li>
</ul>
<!-- Tab Content -->
<div class="tab-content" id="pills-tabContent">
  <div class="tab-pane fade show active" id="pills-mobility" role="tabpanel" aria-labelledby="pills-mobility-tab" tabindex="0">
    <div class="cards">
      <% @exercises.where(category: 'Mobility').each do |exercise| %>
        <%= render 'shared/exercise_list_card', exercise: exercise %>
      <% end %>
    </div>
  </div>
  <div class="tab-pane fade" id="pills-skills" role="tabpanel" aria-labelledby="pills-skills-tab" tabindex="0">
    <div class="cards">
      <% @exercises.where(category: 'Skills').each do |exercise| %>
        <%= render 'shared/exercise_list_card', exercise: exercise %>
      <% end %>
    </div>
  </div>
  <div class="tab-pane fade" id="pills-upperbody" role="tabpanel" aria-labelledby="pills-upperbody-tab" tabindex="0">
    <div class="cards">
      <% @exercises.where(category: 'Push/Pull Upper Body').each do |exercise| %>
        <%= render 'shared/exercise_list_card', exercise: exercise %>
      <% end %>
    </div>
  </div>
  <div class="tab-pane fade" id="pills-core" role="tabpanel" aria-labelledby="pills-core-tab" tabindex="0">
    <div class="cards">
      <% @exercises.where(category: 'Core').each do |exercise| %>
        <%= render 'shared/exercise_list_card', exercise: exercise %>
      <% end %>
    </div>
  </div>
  <div class="tab-pane fade" id="pills-lowerbody" role="tabpanel" aria-labelledby="pills-lowerbody-tab" tabindex="0">
    <div class="cards">
      <% @exercises.where(category: 'Lower Body').each do |exercise| %>
        <%= render 'shared/exercise_list_card', exercise: exercise %>
      <% end %>
    </div>
  </div>
</div>

app/views/exercises/show.html.erb
<div>
  <h1 class="custom-margin <%= @exercise.exercise_type %>">
    <%#= @workout_session.workout.name %>
    <%= @exercise.name %>
  </h1>

  <div class="d-flex justify-content-between align-items-center">
    <div class="exercise-info-div">
      <%# sets and reps here: %>
      <span class="exercise-info">
        <i class="fa-solid fa-dumbbell"></i> <%= @exercise.sets %> sets
        <% if @exercise.lower_reps.nil? && @exercise.upper_reps.nil? %>
          <i class="fa-solid fa-stopwatch ms-3"></i> <%= @exercise.hold_time %> s hold
        <% else %>
          <i class="fa-solid fa-repeat ms-3"></i> <%= @exercise.lower_reps %>-<%= @exercise.upper_reps %> reps
        <% end %>
      </span>
      <span><i class="fa-regular fa-circle-pause"></i> <%= @exercise.rest %>s rest</span>
    </div>
      <%# how to link here: %>
      <%= render 'shared/how_to_link', exercise: @exercise, workout_session: @workout_session %>
  </div>


  <%# progress bar here: %>
  <%#= render 'shared/progress_bar', workout_session: @workout_session, exercises: @exercises %>

  <% @sets_done = @workout_session.sets_done(@exercise) %>

  <%# video here %>
  <div class="video">

    <div class="progress-note">
      <h4>You have</h4>
      <h2><%= @exercise.sets - @sets_done.count %></h2>
      <h4>sets remaining!</h4>
    </div>

    <div data-controller="record-video">
      <div>
        <div data-record-video-target="cameraButton">
          <button data-action="click->record-video#showFullScreen" class="camera"><i class="fa-solid fa-camera fa-2xl"></i></button>
        </div>
        <div data-record-video-target="videoReplace" class="record-frame d-none">
          <button id="start" data-record-video-target="start" data-action="click->record-video#record"><i class="fa-solid fa-circle"></i></button>
          <button id="stop" data-record-video-target="stop" data-action="click->record-video#replace"><i class="fa-solid fa-stop"></i></button>
          <div>
            <%# <button data-action="click->record-video#showFullScreen">Toggle Full Screen</button> %>
            <video autoplay muted data-record-video-target="live"  width="100px" height="100px">
            </video>
          </div>
        </div>
        <div data-record-video-target="video" class="d-none"></div>
      </div>
      <div>
        <h3 class="label">Enter your reps</h3>
        <%= render 'shared/exercise_set_form', set: ExerciseSet.new, exercise: @exercise, workout_session: @workout_session %>
      </div>
      <div>
        <h3 class="label" data-record-video-target="duration"></h3>
      </div>
    </div>
  </div>

  <div class="d-flex justify-content-between">
    <%= link_to "Back", workout_session_path(@workout_session, active_tab: @exercise.id), class: 'rounded-button delayed'%>
    <% unless @sets_done.count >= @exercise.sets - 1 %>
      <%= link_to "Next", workout_session_exercise_path(@workout_session, @exercise), class: 'rounded-button delayed' %>
    <% end %>
  </div>
</div>